#ifndef __MONITOR_PROTOCOL_H
#define __MONITOR_PROTOCOL_H

#pragma pack(1)

/************************************************************************/
/*                        WEB后台与监控中心                             */
/************************************************************************/

#define MONITOR_CMDID_BASE				40000		//监控协议命令ID起始值

//WEB后台登陆请求
#define MONITOR_CMDID_WEB_ACCOUNTLOGIN_REQ		 (MONITOR_CMDID_BASE)

//WEB后台登陆回复
#define MONITOR_CMDID_WEB_ACCOUNTLOGIN_REP		 (MONITOR_CMDID_BASE + 1)

//查询MCU服务器地址请求
#define MONITOR_CMDID_WEB_QUERYSRVADDR_REQ		 (MONITOR_CMDID_BASE + 2)

//查询MCU服务器地址回复
#define MONITOR_CMDID_WEB_QUERYSRVADDR_REP		 (MONITOR_CMDID_BASE + 3)

//操作MCU服务器地址请求
#define MONITOR_CMDID_WEB_OPERATIONSRVADDR_REQ	 (MONITOR_CMDID_BASE + 4)

//操作MCU服务器地址回复
#define MONITOR_CMDID_WEB_OPERATIONSRVADDR_REP	 (MONITOR_CMDID_BASE + 5)

//业务重置请求
#define MONITOR_CMDID_WEB_SERVICERESET_REQ		 (MONITOR_CMDID_BASE + 6)

//业务重置回复
#define MONITOR_CMDID_WEB_SERVICERESET_REP		 (MONITOR_CMDID_BASE + 7)

//服务器重置返回
#define MONITOR_CMDID_WEB_SRVRESET_REQ			(MONITOR_CMDID_BASE + 8)

//服务器重置回复
#define MONITOR_CMDID_WEB_SRVRESET_REP			(MONITOR_CMDID_BASE + 9)

//MCU运行状态请求
#define MONITOR_CMDID_WEB_REALTIMEDATA_REQ		(MONITOR_CMDID_BASE + 10)

//MCU运行状态回复
#define MONITOR_CMDID_WEB_REALTIMEDATA_REP		(MONITOR_CMDID_BASE + 11)

//MCU业务服务列表请求
#define MONITOR_CMDID_WEB_SERVICELIST_REQ		(MONITOR_CMDID_BASE + 12)

//MCU业务服务列表回复
#define MONITOR_CMDID_WEB_SERVICELIST_REP		(MONITOR_CMDID_BASE + 13)

//MCU授权激活请求
#define MONITOR_CMDID_WEB_LICENSEACTIVATED_REQ	(MONITOR_CMDID_BASE + 16)

//MCU授权激活回复
#define MONITOR_CMDID_WEB_LICENSEACTIVATED_REP	(MONITOR_CMDID_BASE + 17)

//打开/关闭动态地址注册功能
#define MONITOR_CMDID_WEB_ARQS_REQ				(MONITOR_CMDID_BASE + 18)

//动态地址注册功能返回
#define MONITOR_CMDID_WEB_ARQS_REP				(MONITOR_CMDID_BASE + 19)

//查询服务器网络连接类型请求
#define MONITOR_CMDID_WEB_QUERY_NETCONNTYPE_REQ	(MONITOR_CMDID_BASE + 20)

//查询服务器网络连接类型回复
#define MONITOR_CMDID_WEB_QUERY_NETCONNTYPE_REP	(MONITOR_CMDID_BASE + 21)

//设置服务器网络连接类型请求
#define MONITOR_CMDID_WEB_SET_NETCONNTYPE_REQ	(MONITOR_CMDID_BASE + 22)

//设置服务器网络连接类型回复
#define MONITOR_CMDID_WEB_SET_NETCONNTYPE_REP	(MONITOR_CMDID_BASE + 23)

//生成注册文件请求
#define MONITOR_CMDID_WEB_CREATEREGFILE_REQ		(MONITOR_CMDID_BASE + 24)

//MCU生成注册文件回复
#define MONITOR_CMDID_WEB_CREATEREGFILE_REP		(MONITOR_CMDID_BASE + 25)

//更新设备ID请求
#define MONITOR_CMDID_WEB_UPDATEDEVID_REQ		(MONITOR_CMDID_BASE + 26)

//更新设备ID回复
#define MONITOR_CMDID_WEB_UPDATEDEVID_REP		(MONITOR_CMDID_BASE + 27)

#pragma pack()

#endif//__MONITOR_PROTOCOL_H
;